# config.py

# [Controlo de Simulação]
CENARIO_SEMPRE_NOVO = True

# [Geografia e Topologia]
COORDENADAS = (41.8058, -6.7572) # Bragança
RAIO_M = 200
LARGURA_RUA = 10
AREA_MEDIA_LOTE = 350
ESPACO_ENTRE_LOTES = 2.0
DENSIDADE_PREDIOS = 0.8
ALTURA_MIN = 5
ALTURA_MAX = 45

# [Gestão de Frota e Logística]
NUM_DRONES_DISPONIVEIS = 2
NUM_ENTREGAS_TOTAL = 5
DISTANCIA_MIN_ENTREGA = 40.0
MARGEM_SEGURANCA_MAPA = 15.0
ZONA_LIVRE_CD = 15.0
ZONA_LIVRE_ENTREGA = 5.0

# [Parâmetros Físicos do Drone]
DRONE_RAIO_M = 2.0
DRONE_ALTURA_VOO = 25
DRONE_VELOCIDADE_MS = 12
DRONE_CARGA_KG = 3.0

# [Caminho de Salvamento de Logs]
CAMINHO_LOG = r"C:\Users\Forlin\Dissertação\log"